# Change these first
owner: oetztal # Your GitHub organization or username, where this repository lives
repo: upptime-infra # The name of this repository

sites:
  - name: Main Web
    url: https://$PUBLIC_WEB
    ipv6: true
  - name: Internal Web
    url: $INTERNAL_DOMAIN
    port: 80
    check: "tcp-ping"
    ipv6: true
  - name: Topic1 Web
    url: https://$TOPIC1_WEB
    ipv6: true
  - name: Web
    url: https://$INTERNAL_DOMAIN
    ipv6: true
  - name: Cloud
    url: https://cloud.$INTERNAL_DOMAIN
    ipv6: true
  - name: Git
    url: https://git.$INTERNAL_DOMAIN
    ipv6: true
  - name: Mail
    url: https://mail.$INTERNAL_DOMAIN
    ipv6: true
  - name: Mail Submission
    check: "tcp-ping"
    url: mail.$INTERNAL_DOMAIN
    port: 587
    ipv6: false
  - name: Mail IMAP
    check: "tcp-ping"
    url: mail.$INTERNAL_DOMAIN
    port: 143
    ipv6: false
  - name: XMPP
    check: "tcp-ping"
    url: $INTERNAL_DOMAIN
    port: 5222
    ipv6: false
  - name: Metrics
    url: https://mail.$INTERNAL_DOMAIN
    ipv6: true
  - name: Pad
    url: https://pad.$INTERNAL_DOMAIN
    ipv6: true
  - name: Documentation
    url: https://doc.$INTERNAL_DOMAIN
    ipv6: true
  - name: Wiki
    url: https://wiki.$INTERNAL_DOMAIN
    ipv6: true
  - name: SSO
    url: https://sso.$INTERNAL_DOMAIN/realms/$INTERNAL_REALM/.well-known/openid-configuration
    ipv6: true

assignees:
  - wuan

status-website:
  baseUrl: /upptime-infra
  name: Infra status
  navbar:
    - title: Status
      href: /upptime-infra
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
